name: PR Merged to master

on:
  push:
    branches:
      - master
jobs:
  push-nuget-package:
    name: Push Nuget Package from Master after PR is merged
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cangulo/cangulo.build-docker-gh-action@master
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.NUGET_PUSH_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.NUGET_PUSH_AWS_SECRET }}
          aws-region: eu-west-1
      - name: Install AWS Credentials tools
        run: |
          export PATH="$PATH:/root/.dotnet/tools"
          dotnet tool install -g AWS.CodeArtifact.NuGet.CredentialProvider
          dotnet codeartifact-creds install
      - name: Add CodeArtifact nuget source
        id: setup-remote-nuget
        run: |
          domain="cangulo-common-domain"
          repo="cangulo-common-repo-internal"
          sourceName="cangulo-common-repo-internal"
          accountId=$(aws sts get-caller-identity --query Account --output text)
          sourceEndPoint=$(aws codeartifact get-repository-endpoint --domain $domain --domain-owner $accountId --repository $repo --format nuget --output text)
          sourceEndPoint=$sourceEndPoint"v3/index.json"
          authToken=$(aws codeartifact get-authorization-token --domain $domain --query authorizationToken)
          dotnet nuget add source $sourceEndPoint -n $sourceName -p $authToken -u aws --store-password-in-clear-text
          echo ::set-output name=SOURCE_NAME::$(echo $sourceName)
      - name: Construct GetNumberLastPRMerged Request
        id: get-lastpr-request
        run: |
          GET_LAST_PR_MERGED_REQUEST=$(cat <<-END
            {
                \"requestModel\":\"GetNumberLastPRMerged\",
                \"originator\":\"${{ github.actor }}-${{ github.event_name }}\",
                \"TargetBranch\":\"master\",
                \"repositoryId\":${{ github.event.repository.id }}
            }
          END
          )
          echo ::set-output name=REQUEST::$(echo $GET_LAST_PR_MERGED_REQUEST)
          echo "$GET_LAST_PR_MERGED_REQUEST"
      - name: GetNumberLastPRMerged Nuke
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_FILE_PATH: "./artifacs"
        run: ./cangulo.build/cangulo.build --root . --target GenericRequestHandler --requestJSON "${{ steps.get-lastpr-request.outputs.REQUEST }}" --verbosity verbose
      - name: GetNumberLastPRMerged Response
        id: get-lastpr-response
        run: |
          lastPullRequestNumber=$(jq . ./artifacs/GetNumberLastPRMerged_RESPONSE.json -c | jq -aR)
          echo $lastPullRequestNumber
          echo ::set-output name=RESPONSE::$(echo $lastPullRequestNumber)
      - name: Construct GetModifiedProjectsInPR Request
        id: modified-projects-request
        run: |
          GET_MODIFIED_PROJECTS_REQUEST=$(cat <<-END
            {
                \"requestModel\":\"GetModifiedProjectsInPR\",
                \"originator\":\"${{ github.actor }}-${{ github.event_name }}\",
                \"pullRequestNumber\":${{ steps.get-lastpr-response.outputs.RESPONSE }},
                \"repositoryId\":${{ github.event.repository.id }}
            }
          END
          )
          echo ::set-output name=REQUEST::$(echo $GET_MODIFIED_PROJECTS_REQUEST)
          echo "$GET_MODIFIED_PROJECTS_REQUEST"
      - name: GetModifiedProjectsInPR Nuke
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OUTPUT_FILE_PATH: "./artifacs"
        run: ./cangulo.build/cangulo.build --root . --target GenericRequestHandler --requestJSON "${{ steps.modified-projects-request.outputs.REQUEST }}" --verbosity verbose
      - name: GetModifiedProjectsInPR Response
        run: cat ./artifacs/GetModifiedProjectsInPR_RESPONSE.json
      - name: Construct PackProjects Request
        id: request-pack-nuget
        run: |
          PACK_PROJECT=$(cat <<-END
            {
                \"requestModel\":\"PackProjects\",
                \"originator\":\"${{ github.actor }}-${{ github.event_name }}\",
                \"creationMode\": \"Release\", 
                \"projects\": $(jq . ./artifacs/GetModifiedProjectsInPR_RESPONSE.json -c | jq -aR), 
                \"outputFolder\": \"artifacts\", 
                \"branch\": \"$(git branch --show-current)\"
            }
          END
          )
          echo ::set-output name=PACK_PROJECT::$(echo $PACK_PROJECT)
          echo "$PACK_PROJECT"
      - name: Execute PackProjects Nuke
        run: ./cangulo.build/cangulo.build --root . --target GenericRequestHandler --requestJSON "${{ steps.request-pack-nuget.outputs.PACK_PROJECT }}" --verbosity verbose
      - name: Construct PushNugetPackages Request
        id: request-push-nuget
        run: |
          targetNugetRepository=${{ steps.setup-remote-nuget.outputs.SOURCE_NAME }}
          PUSH_NUGET=$(cat <<-END
            {
                \"requestModel\":\"PushNugetPackages\",
                \"originator\":\"${{ github.actor }}-${{ github.event_name }}\",
                \"nugetPackagesLocation\": \"artifacts\", 
                \"targetNugetRepository\": \"${targetNugetRepository}\",
                \"commentToPrRequest\":{
                  \"originator\":\"${{ github.actor }}-${{ github.event_name }}\",
                  \"pullRequestNumber\":${{ steps.get-lastpr-response.outputs.RESPONSE }},
                  \"repositoryId\":${{ github.event.repository.id }}
                }
            }
          END
          )
          echo ::set-output name=PUSH_NUGET::$(echo $PUSH_NUGET)
          echo "$PUSH_NUGET"
      - name: Execute PushNugetPackages Nuke
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: ./cangulo.build/cangulo.build --root . --target GenericRequestHandler --requestJSON "${{ steps.request-push-nuget.outputs.PUSH_NUGET }}" --verbosity verbose
