name: Testing cangulo.build

on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: Downloading cangulo.build
    steps:
      - name: Download cangulo.build
        uses: cangulo/cangulo.cicd-gh-action@@master
      - name: List files in root
        run: |
          echo "folder in root"
          ls -la
