name: "cangulo.cicd"
description: "Download cangulo.cicd to $GITHUB_WORKSPACE path"
inputs:
  version:
    description: "Version as 'x.y.z' or 'latest'"
    required: true
    default: "latest"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.version }}
